# Generated by Django 6.0.2 on 2026-02-26 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_bookings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bookings",
            new_name="Booking",
        ),
    ]
