# Generated by Django 6.0.2 on 2026-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_bookings_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
    ]
