# Generated by Django 6.0.2 on 2026-03-05 05:31

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_room_is_empty"),
    ]

    operations = [
        BtreeGistExtension(),
    ]
