# Generated by Django 6.0.2 on 2026-03-05 07:18

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_auto_20260305_1031"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("room", "="),
                    (
                        models.Func(
                            "start_date",
                            "end_date",
                            models.Value("[]"),
                            function="daterange",
                        ),
                        "&&",
                    ),
                ],
                name="prevent_double_booking",
            ),
        ),
    ]
